function removetrTicks
%UNTITLED 移除图片右上部分的刻度
%   此处提供详细说明
box off
ax = axes('Position',get(gca,'Position'),...
    'Color','none',...
    'XAxisLocation','top',...
    'YAxisLocation','right',...
    'XColor','k',...
    'YColor','k');
set(ax,'YTick', []);
set(ax,'XTick', []);
end