function networkNoShadowingShadowFadingMap = LTE_init_generate_NoShadowing_shadow_fading_map(eNodeBs)
% Generates a structure similar to the Claussen Shadow Fading Map but
% without any shadowing (to deactivate shadow fading)
% (c) Stefan Schwarz, INTHFT, 2010

global LTE_config;

%% Generate the shadow fading map
% print_log(1,'Generating Claussen space-correlated shadow fading map\n');
networkNoShadowingShadowFadingMap = channel_gain_wrappers.shadowFadingMapClaussen(...
    LTE_config.shadow_fading_map_resolution,...
    LTE_config.roi_x,...
    LTE_config.roi_y,...
    LTE_config.shadow_fading_n_neighbors,...
    eNodeBs,...
    LTE_config.shadow_fading_mean,...
    LTE_config.shadow_fading_sd,...
    LTE_config.r_eNodeBs);